Rekla.Web.UI/Areas/Users/Controllers/ServiceRequestsController.cs
using Rekla.ViewModel.Task;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Rekla.Web.UI.Areas.Users.Controllers
{
    public class ServiceRequestsController : Controller
    {
        private ServiceRequestFactory _Factory; 
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            if (Session["Sr"] == null)
            {
                Session["Sr"] = _Factory = new ServiceRequestFactory();
            }
            else
            {
                _Factory = (ServiceRequestFactory)Session["Sr"];
            }
            base.OnActionExecuting(filterContext);
        }
        // GET: Users/ServiceRequests
        public ActionResult Index()
        {
            return View(_Factory.ViewModel);
        }

        public ActionResult Details(string Id)
        {
            return View(_Factory.ViewModel.First(i => i.Id == Id));
        }
        public ActionResult CompleteTask(string Id)
        {
            _Factory.CompleteTask(Id);
            Session["Sr"] = _Factory;
            return RedirectToAction("Index");
        }
        
    }
}

Rekla.Web.UI/Areas/Users/Views/ServiceRequests/Details.cshtml
@model Rekla.ViewModel.Task.RequstedServiceViewModel

@{
    ViewBag.Title = "Details";
}

<section class="features">

    <div class="container">
        <h4>Requsted Service Details</h4>

        <table class="table table-bordered table-striped">
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Service)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Service)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Breif)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Breif)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Area)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Area)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.City)
                </td>

                <td>
                    @Html.DisplayFor(model => model.City)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.OnDateTime)
                </td>

                <td>
                    @Html.DisplayFor(model => model.OnDateTime)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Email)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Email)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Address)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Address)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.MobileNo)
                </td>

                <td>
                    @Html.DisplayFor(model => model.MobileNo)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Completed)
                </td>

                <td>
                    @(Model.Completed?"Completed":"Pending")
                </td>
            </tr>
        </table>
    </div>
</section>

Rekla.Web.UI/Areas/Users/Views/ServiceRequests/Index.cshtml
@model IEnumerable<Rekla.ViewModel.Task.RequstedServiceViewModel>

<section class="features">

    <div class="container">
        <h3>History Of Services</h3>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Service)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Breif)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Area)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OnDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MobileNo)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Completed)
                </th>
            </tr>

            @foreach (var item in Model) {
        <tr class="@(item.Completed?"success":"danger")">
            <td>
                @Html.ActionLink(item.Service, "Details", new { id = item.Id })
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Breif)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OnDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNo)
            </td>
            <td>
                @(item.Completed ? "Completed" : "Pending")

                <a href="@Url.Action("CompleteTask", "ServiceRequests",new {id=item.Id})">Complete</a>
            </td>
        </tr>
    }

        </table>
    </div>
</section>